### ISSUE TITLE
multiple english site causing issue with hreflang missing return link

### ISSUE THREAD

**Issue by cakasuma** [microapps/gatsby-plugin-react-i18next#12]
we have `/` for english path, and we also have `/en` for english path, can we only have either one, i have issue with hreflang missing return link because of this

**Comment by jimmyn** [comment]
Fixed in [v0.0.21](https://github.com/microapps/gatsby-plugin-react-i18next/releases/tag/v0.0.21)

**Comment by cakasuma** [comment]
Hi @jimmyn , thank you for fixing it, however, its still not properly working in SEO technical test, for hreflang to be working, it needs to be self-referencing as well.

for e.g, supposedly i have 2 language, `en` and `id`:

www.xdomainx.com will have 2 hreflangs
```
<link rel='alternate'  hreflang='en' href='www.xdomainx.com' />
<link rel='alternate'  hreflang='id' href='www.xdomainx.com/id' />
```

www.xdomainx.com/id will also have 2 hreflangs
```
<link rel='alternate'  hreflang='en' href='www.xdomainx.com' />
<link rel='alternate'  hreflang='id' href='www.xdomainx.com/id' />
```

**Comment by cakasuma** [comment]
currently whats happening because you tried to filter `lng !== lang`

www.xdomainx.com will only have 1 hreflang
```
<link rel='alternate'  hreflang='id' href='www.xdomainx.com/id' />
```

www.xdomainx.com/id will also only have 1 hreflang
```
<link rel='alternate'  hreflang='en' href='www.xdomainx.com' />
```

**Comment by cakasuma** [comment]
adding a PR for possible fix https://github.com/microapps/gatsby-plugin-react-i18next/pull/15, please help to review

**Comment by jimmyn** [comment]
As far as I know, `canonical` links should be self-referencing, not sure that you need a `canonical` link and an `alternative` pointing to the same URL, doesn't make sense to me. Do you have any good source where this is described? What SEO technical test are you using?

**Comment by jimmyn** [comment]
@cakasuma Ok, I did some research and it seems that you are right.
